[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_lend_borrow = "45Td8vFirPb7pJhzomUSLLKLu3onNPz4WC9gFvqsci9F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/od0gwu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
